name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Refresh dependencies
        run: sudo apt update
      - name: Install dependencies
        run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -yq --no-install-recommends build-essential debhelper dh-python dpkg-dev python3 python3-distutils-extra po-debconf pyflakes3 lsb-release gnu-efi
      - name: Build package
        run: dpkg-buildpackage --no-sign
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Refresh dependencies
        run: sudo apt update
      - name: Install dependencies
        run: sudo apt install shellcheck -y
      - name: Run pre-commit hooks
        run: |
          ./contrib/setup
          source venv/bin/activate
          sed -i "/no-commit-to-branch/,+1d" .pre-commit-config.yaml
          pre-commit run --all-files
